/** Machine-readable reasons the API refuses a request. Mirrors the backend. */
export enum ApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  PERMISSION_REQUIRED = 'PERMISSION_REQUIRED',
  CONNECTION_NOT_SYNCABLE = 'CONNECTION_NOT_SYNCABLE',
  CREDENTIALS_REJECTED = 'CREDENTIALS_REJECTED',
  ACCOUNT_MISMATCH = 'ACCOUNT_MISMATCH',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
}
