/** Machine-readable reasons the email endpoints refuse a request. Mirrors the backend. */
export enum EmailApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  PERMISSION_REQUIRED = 'PERMISSION_REQUIRED',
  RATE_LIMITED = 'RATE_LIMITED',
  CONTACT_EXISTS = 'CONTACT_EXISTS',
  DRAFT_LOCKED = 'DRAFT_LOCKED',
  EMAIL_NOT_CONFIGURED = 'EMAIL_NOT_CONFIGURED',
  NO_RECIPIENTS = 'NO_RECIPIENTS',
  TOO_MANY_RECIPIENTS = 'TOO_MANY_RECIPIENTS',
  NO_GAMES = 'NO_GAMES',
  RECIPIENT_COUNT_CHANGED = 'RECIPIENT_COUNT_CHANGED',
  NO_EMAIL_ON_ACCOUNT = 'NO_EMAIL_ON_ACCOUNT',
}
