/** Machine-readable reasons the auth layer refuses a request. */
export enum AuthErrorCode {
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  NO_MEMBERSHIP = 'NO_MEMBERSHIP',
  ROLE_NOT_ASSUMABLE = 'ROLE_NOT_ASSUMABLE',
  INVALID_TENANT_HEADER = 'INVALID_TENANT_HEADER',
  PERMISSION_REQUIRED = 'PERMISSION_REQUIRED',
  AUTH_UNAVAILABLE = 'AUTH_UNAVAILABLE',
}
